### ISSUE TITLE
simple-js-oauth displays `Error: secret option required for sessions` in log and UI 

### ISSUE THREAD

**Issue by jcranfordupgrade** [plaid/tutorial-resources#22]
I tried running simple-js-oauth. It starts, but I get the error when I open http://localhost:8000. See the error at the end of this issue.

To workaround the problem, I googled the error and found a one-line workaround. I edited server.js to set a missing secret in the `app` object.
```
const app = express();
app.use(session({ secret: 'somevalue' })); // The fix
const moment = require("moment");
```

Please consider adding the missing secret, otherwise simple-js-oauth doesn't run properly and gives the following error in UI and log.
```
Error: secret option required for sessions
    at session (/Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express-session/index.js:200:12)
    at Layer.handle [as handle_request] (/Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express/lib/router/index.js:323:13)
    at /Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express/lib/router/index.js:341:12)
    at next (/Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express/lib/router/index.js:323:13)
    at /Users/jcranford/github/workspaces/plaid/tutorial-resources/worktree/oauth2/vanilla-js-oauth/start/node_modules/express/lib/router/index.js:284:7
```

**Comment by phoenixy1** [comment]
Hmm, I took a look but I wasn't able to reproduce this issue as described. When running the code according to the README, it worked. Also, there is no folder called simple-js-oauth in this repo, although there is vanilla-js-oauth, which already sets the secret in the app object in server.js line 13.
